iTracker Source Code 09212020/AutoIncidentTracking/Models/T3Group.cs
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

/// <remarks>
/// ================================================================================
/// MODULE:  T3Group.cs
///         
/// PURPOSE:
/// This class represents a single Tier3 group and limits the selection values 
/// for groups within manufacturing areas.
///         
/// Copyright:    ©2020 by E2i, Inc.
/// Created Date: 2020-04-29
/// Author:       Brad Robbins (brobbins@e2i.net)
///   
/// --------------------------------------------------------------------------------
/// Revision History:			
/// Author          Date        Description
/// Brad Robbins	2020-04-29  Initial version
/// ================================================================================
/// </remarks>

namespace IncidentTracking.Models
{
    ///<summary>Represents a single Tier3 group object.</summary>
    public class T3Group
    {
        ///<summary>Gets/sets the T3Group identifier</summary>
        [Key]
        public int T3GroupId { get; set; }

        ///<summary>Gets/sets the group name</summary>
        [Required(ErrorMessage = "Group name is required.")]
        [StringLength(50, ErrorMessage = "Group name cannot be more than 50 characters.")]
        public string Name { get; set; }

        ///<summary>Gets/sets the SME name.</summary>
        [DisplayName("SME Name")]
        [Required(ErrorMessage = "SME name is required.")]
        [StringLength(50, ErrorMessage = "SME name cannot be more than 50 characters.")]
        public string SmeName { get; set; }

        ///<summary>Gets/sets the SME email address.</summary>
        [DisplayName("SME Email Address")]
        [Required(ErrorMessage = "SME email address is required.")]
        [StringLength(100, ErrorMessage = "SME email address cannot be more than 100 characters.")]
        public string SmeEmailAddress { get; set; }

        ///<summary>Gets/sets the ReplyTo email address.</summary>
        [DisplayName("ReplyTo Email Address")]
        [Required(ErrorMessage = "ReplyTo email address is required.")]
        [StringLength(100, ErrorMessage = "ReplyTo email address cannot be more than 100 characters.")]
        public string ReplyToEmailAddress { get; set; }

        #region EF Navigation Fields
        ///<summary>Gets/sets the related manufacturing areas.</summary>
        public ICollection<ManufacturingArea> ManufacturingAreas { get; set; }
        #endregion EF Navigation Fields
    }
}

iTracker Source Code 09212020/AutoIncidentTracking/Controllers/ManufacturingAreasController.cs
using IncidentTracking.Data;
using IncidentTracking.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using System;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;

/// <remarks>
/// ================================================================================
/// MODULE:  ManufacturingAreasController.cs
///         
/// PURPOSE:
/// This class represents the manufacturing area controller which is responsible for 
/// handling all interactions between the manufacturing areas model, related view 
/// models and associated views (user displays).
///         
/// Copyright:    ©2018 by E2i, Inc.
/// Created Date: 2018-09-24
/// Author:       Brad Robbins (brobbins@e2i.net)
///   
/// --------------------------------------------------------------------------------
/// Revision History:			
/// Author          Date        Description
/// Brad Robbins	2018-10-30  Initial version
/// Brad Robbins    2019-05-24  Added ReportLabel for creating/editing
/// Brad Robbins    2019-09-24  Added support for SME and Mgr fields
/// Brad Robbins    2020-04-29  Added support for T3Group
/// Brad Robbins    2020-06-12  Added logging and index view model
/// Brad Robbins    2020-06-23  Corrected sorting error for description
/// ================================================================================
/// </remarks>

namespace IncidentTracking.Controllers
{
    [Authorize(Roles = "cslg1.cslg.net\\KANBPL_APP_ENG_ES11_Admin")]
    public class ManufacturingAreasController : BaseController
    {
        public ManufacturingAreasController(ApplicationDbContext context, IConfiguration config, ILogger<ManufacturingAreasController> logger)
            : base(context, config, logger){}

        // GET: ManufacturingAreas
        public async Task<IActionResult> Index(string sortOrder, int? page)
        {
            Logger.LogTrace("ManufacturingAreas/Index called with [{sortOrder}] and page [{page}]", sortOrder, page);
            //setup sorting data
            ViewData["CurrentSort"] = sortOrder;
            ViewData["NameSortParam"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewData["DescriptionSortParam"] = sortOrder == "dscptn" ? "dscptn_desc" : "dscptn";

            var list = DatabaseContext.ManufacturingAreas
                .Select(m => new ManufacturingAreaIndexViewModel 
                { 
                    ManufacturingAreaId = m.ManufacturingAreaId,
                    Name = m.Name, 
                    Description = m.Description
                }).AsNoTracking();

            switch (sortOrder)
            {
                case "name_desc": list = list.OrderByDescending(m => m.Name); break;
                case "dscptn": list = list.OrderBy(m => m.ManufacturingAreaId); break;
                case "dscptn_desc": list = list.OrderByDescending(m => m.ManufacturingAreaId); break;
                default: list = list.OrderBy(m => m.Name); break;
            }

            var outList = await PaginatedList<ManufacturingAreaIndexViewModel>
                .CreateAsync(list, page ?? 1, PageSize);

            return View("Index", outList);
        }
        
        // GET: ManufacturingAreas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            Logger.LogTrace("ManufacturingAreas/Details called with [{id}]", id);
            if (id == null)
                return NotFound();

            var manufacturingArea = await DatabaseContext.ManufacturingAreas
                .AsNoTracking()
                .Include(m => m.ControlSystems)
                .Include(m => m.T3Group)
                .FirstOrDefaultAsync(m => m.ManufacturingAreaId == id);
            if (manufacturingArea == null)
                return NotFound();

            return View(manufacturingArea);
        }

        // GET: ManufacturingAreas/Create
        public async Task<IActionResult> Create() 
        {
            Logger.LogTrace("ManufacturingAreas/Create[Get] called");
            //load the select (drop down) list
            ViewData["T3GroupId"] = await GetT3GroupsSelectListAsync();
            return View(new ManufacturingArea());
        } 

        // POST: ManufacturingAreas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ManufacturingAreaId,Name,ReportLabel,SmeName,SmeEmailAddress,MgrName,MgrEmailAddress,ReplyToEmailAddress,T3GroupId")] ManufacturingArea manufacturingArea)
        {
            Logger.LogTrace("ManufacturingAreas/Create[Post] called");
            if (ModelState.IsValid)
            {
                try
                {
                    DatabaseContext.Add(manufacturingArea);
                    await DatabaseContext.SaveChangesAsync();
                    TempData["Message"] = "Area has been added.";
                    Logger.LogInformation("{user} added Manufacturing Area[{name}]", UserName, manufacturingArea.Name);
                    return RedirectToAction(nameof(Index));
                }
                catch (DbUpdateException)
                {
                    string message = "Cannot add area because ID is in use.";
                    TempData["Error"] = message;
                    Logger.LogDebug(message);
                }
                catch (SqlException ex)
                {
                    string message = $"Cannot add area because of a database error: {ex.Message}";
                    TempData["Error"] = message;
                    Logger.LogError(message);
                }
                catch (Exception ex)
                {
                    string message = $"Cannot add area because of a general error: {ex.Message}";
                    TempData["Error"] = message;
                    Logger.LogError(message);
                }
            }
            
            //load the select (drop down) list
            ViewData["T3GroupId"] =
                await GetT3GroupsSelectListAsync(manufacturingArea.T3GroupId);

            return View(manufacturingArea);
        }

        // GET: ManufacturingAreas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            Logger.LogTrace("ManufacturingAreas/Edit[GET] called with [{id}]", id);
            if (id == null)
                return NotFound();

            var manufacturingArea = await DatabaseContext.ManufacturingAreas.FindAsync(id);
            if (manufacturingArea == null)
                return NotFound();
                
            //load the select (drop down) list
            ViewData["T3GroupId"] =
                await GetT3GroupsSelectListAsync(manufacturingArea.T3GroupId);

            return View(manufacturingArea);
        }

        // POST: ManufacturingAreas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ManufacturingAreaId,Name,ReportLabel,SmeName,SmeEmailAddress,MgrName,MgrEmailAddress,ReplyToEmailAddress,T3GroupId")] ManufacturingArea manufacturingArea)
        {
            Logger.LogTrace("ManufacturingAreas/Edit[POST] called with [{id}]", id);
            if (id != manufacturingArea.ManufacturingAreaId)
                return NotFound();
            
            if (ModelState.IsValid)
            {
                try
                {
                    DatabaseContext.Update(manufacturingArea);
                    await DatabaseContext.SaveChangesAsync();
                    Logger.LogInformation("{user} updated ManufacturingArea[{name}]", UserName, manufacturingArea.Name);
                    TempData["Message"] = "Area has been updated.";
                }
                catch (DbUpdateConcurrencyException ex)
                {
                    string message;
                    if (!ManufacturingAreaExists(manufacturingArea.ManufacturingAreaId))
                        message = $"Cannot edit area because it no longer exists.";
                    else
                        message = $"Cannot edit area because of a concurrency error: {ex.Message}";
                    TempData["Error"] = message;
                    Logger.LogError("Error updating ManufacturingArea[{id}] because of {message}", id, message);
                }
                catch (Exception ex)
                {
                    string message = $"Cannot edit area because of a general error: {ex.Message}";
                    TempData["Error"] = message;
                    Logger.LogError("Error updating ManufacturingArea[{id}] because of {message}", id, message);
                }
                return RedirectToAction(nameof(Index));
            }
            
            //load the select (drop down) list
            ViewData["T3GroupId"] =
                await GetT3GroupsSelectListAsync(manufacturingArea.T3GroupId);

            return View(manufacturingArea);
        }

        // GET: ManufacturingAreas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            Logger.LogTrace("ManufacturingAreas/Delete[GET] called with [{id}]", id);
            if (id == null)
                return NotFound();

            var manufacturingArea = await DatabaseContext.ManufacturingAreas
                .FirstOrDefaultAsync(m => m.ManufacturingAreaId == id);
            if (manufacturingArea == null)
                return NotFound();
            
            return View(manufacturingArea);
        }

iTracker Source Code 09212020/AutoIncidentTracking/Views/T3Groups/AddEditPartialView.cshtml
@model IncidentTracking.Models.T3Group
@*
    * ================================================================================
    * MODULE:  T3Groups\AddEditPartialView.cshtml
    *
    * PURPOSE:
    * This view supports adding/editing Tier 3 groups.
    *
    * Copyright:    ©2020 by E2i, Inc.
    * Created Date: 2020-04-29
    * Author:       Brad Robbins (brobbins@e2i.net)
    *
    * --------------------------------------------------------------------------------
    * Revision History:
    * Author           Date        Description
    * Brad Robbins	   2020-04-29  Initial version
    * ================================================================================
*@

<div class="row">
    <div class="col-md-4">
    
        <div class="form-group">
            <label asp-for="T3GroupId" class="control-label"></label>
            <input asp-for="T3GroupId" class="form-control" placeholder="Required unique group number" />
            <span asp-validation-for="T3GroupId" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Name" class="control-label"></label>
            <input asp-for="Name" class="form-control" placeholder="Required unique group name" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="SmeName" class="control-label"></label>
            <input asp-for="SmeName" class="form-control" placeholder="SME name" />
            <span asp-validation-for="SmeName" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="SmeEmailAddress" class="control-label"></label>
            <input asp-for="SmeEmailAddress" class="form-control" placeholder="SME email address" />
            <span asp-validation-for="SmeEmailAddress" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="ReplyToEmailAddress" class="control-label"></label>
            <input asp-for="ReplyToEmailAddress" class="form-control" placeholder="ReplyTo email address" />
            <span asp-validation-for="ReplyToEmailAddress" class="text-danger"></span>
        </div>
    </div>
</div>

iTracker Source Code 09212020/AutoIncidentTracking/Views/T3Groups/Create.cshtml
@model IncidentTracking.Models.T3Group
@*
    * ================================================================================
    * MODULE:  T3Groups\Create.cshtml
    *
    * PURPOSE:
    * This view supports adding new Tier 3 groups.
    *
    * Copyright:    ©2020 by E2i, Inc.
    * Created Date: 2020-04-29
    * Author:       Brad Robbins (brobbins@e2i.net)
    *
    * --------------------------------------------------------------------------------
    * Revision History:
    * Author          Date        Description
    * Brad Robbins	  2020-04-29  Initial version
    * ================================================================================
*@
@{
    ViewData["Title"] = "Create";
}

<h2>Add Tier 3 Group</h2>
<p class="alert-danger">@TempData["Error"]</p>
<hr />

<form asp-action="Create" autocomplete="off">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    @{ await Html.RenderPartialAsync("AddEditPartialView"); }
    <div class="form-group">
        <input type="submit" value="Create" class="btn btn-default" />
    </div>
</form>
  
<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

iTracker Source Code 09212020/AutoIncidentTracking/Views/T3Groups/Delete.cshtml
@model IncidentTracking.Models.T3Group
@*
    * ================================================================================
    * MODULE:  T3Groups\Delete.cshtml
    *
    * PURPOSE:
    * This view supports deleting Tier 3 groups.
    *
    * Copyright:    ©2020 by E2i, Inc.
    * Created Date: 2020-04-29
    * Author:       Brad Robbins (brobbins@e2i.net)
    *
    * --------------------------------------------------------------------------------
    * Revision History:
    * Author          Date        Description
    * Brad Robbins	  2020-04-29  Initial version
    * ================================================================================
*@
@{
    ViewData["Title"] = "Delete";
}

<h2>Delete Tier 3 Group</h2>

<h4>Are you sure you want to delete this group?</h4>
<hr/>

<div>
    <dl class="dl-horizontal">
        <dt>Group Name</dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="T3GroupId" />
        <input type="submit" value="Delete" class="btn btn-default" />
        <a asp-action="Index" class="btn btn-default">Cancel</a>
    </form>
</div>

iTracker Source Code 09212020/AutoIncidentTracking/Views/T3Groups/Details.cshtml
@model IncidentTracking.Models.T3Group
@*
    * ================================================================================
    * MODULE:  T3Groups\Details.cshtml
    *
    * PURPOSE:
    * This view supports Tier 3 group details.
    *
    * Copyright:    ©2020 by E2i, Inc.
    * Created Date: 2020-04-29
    * Author:       Brad Robbins (brobbins@e2i.net)
    *
    * --------------------------------------------------------------------------------
    * Revision History:
    * Author          Date        Description
    * Brad Robbins	  2020-04-29  Initial version
    * ================================================================================
*@
@{
    ViewData["Title"] = "Details";
}

<h2>Tier 3 Group Details</h2>
<hr />

<div>
    <dl class="dl-horizontal">
        <dt>Mfg Area Name</dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SmeName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SmeName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SmeEmailAddress)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SmeEmailAddress)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ReplyToEmailAddress)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ReplyToEmailAddress)
        </dd>
    </dl>
</div>
@if (Model.ManufacturingAreas.Count > 0)
{
    <hr />
    <div>
        <h4>Manufacturing Areas</h4>
        <ul>
            @foreach (var m in Model.ManufacturingAreas.OrderBy(a => a.Name))
            {
                <li>
                    <a asp-action="Details" asp-controller="ManufacturingAreas" asp-route-id="@m.ManufacturingAreaId">@m.Name</a>
                </li>
            }
        </ul>
    </div>
}

<div>
    <a asp-action="Edit" asp-route-id="@Model.T3GroupId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

iTracker Source Code 09212020/AutoIncidentTracking/Views/T3Groups/Edit.cshtml
@model IncidentTracking.Models.T3Group
@*
    * ================================================================================
    * MODULE:  T3Groups\Edit.cshtml
    *
    * PURPOSE:
    * This view supports editing Tier 3 groups.
    *
    * Copyright:    ©2020 by E2i, Inc.
    * Created Date: 2020-04-29
    * Author:       Brad Robbins (brobbins@e2i.net)
    *
    * --------------------------------------------------------------------------------
    * Revision History:
    * Author          Date        Description
    * Brad Robbins	  2020-04-29  Initial version
    * ================================================================================
*@
@{
    ViewData["Title"] = "Edit";
}

<h2>Edit Tier 3 Group</h2>
<p class="alert-danger">@TempData["Error"]</p>
<hr />

<form asp-action="Edit" autocomplete="off">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    @{ await Html.RenderPartialAsync("AddEditPartialView"); }
    <div class="form-group">
        <input type="submit" value="Edit" class="btn btn-default" />
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

iTracker Source Code 09212020/AutoIncidentTracking/Views/T3Groups/Index.cshtml
@model IEnumerable<IncidentTracking.Models.T3Group>
@*
    * ================================================================================
    * MODULE:  T3Groups\Index.cshtml
    *
    * PURPOSE:
    * This view supports listing groups.
    *
    * Copyright:    ©2020 by E2i, Inc.
    * Created Date: 2020-04-29
    * Author:       Brad Robbins (brobbins@e2i.net)
    *
    * --------------------------------------------------------------------------------
    * Revision History:
    * Author           Date        Description
    * Brad Robbins	   2020-04-29  Initial version
    * ================================================================================
*@
@{
    ViewData["Title"] = "Index";
}

<h2>Tier 3 Groups</h2>
<p class="alert-success">@TempData["Message"]</p>
<p class="alert-danger">@TempData["Error"]</p>

<p>
    <a asp-action="Create" class="btn btn-default">Create New</a>
</p>
<table class="table table-striped table-condensed">
    <thead>
        <tr>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["NameSortParam"]">Name</a>
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.T3GroupId">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.T3GroupId">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.T3GroupId">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

@await Html.PartialAsync("PagingPartialView")