iTracker Source Code 09212020/AutoIncidentTracking/Controllers/HomeController.cs
using IncidentTracking.Data;
using IncidentTracking.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

/// <remarks>
/// ================================================================================
/// MODULE:  HomeController.cs
///         
/// PURPOSE:
/// This class is responsible for handling all static views (user displays).
///         
/// Copyright:    ©2018 by E2i, Inc.
/// Created Date: 2018-10-30
/// Author:       Brad Robbins (brobbins@e2i.net)
///   
/// --------------------------------------------------------------------------------
/// Revision History:			
/// Author          Date        Description
/// Brad Robbins	2018-10-30  Initial version
/// Brad Robbins    2019-06-03  Revised Index() to use LocalActivityPerformedDateTime
/// Brad Robbins    2020-05-12  Updated to filter out "M" from counts
/// Brad Robbins    2020-06-11  Revised Index() to use IncidentMetrics; added logging
/// ================================================================================
/// </remarks>

namespace IncidentTracking.Controllers
{
    public class HomeController : BaseController
    {
        public HomeController(ApplicationDbContext context, IConfiguration config, ILogger<HomeController> logger)
            : base(context, config, logger){}

        public async Task<IActionResult> Index()
        {
            Logger.LogTrace("Index called");

            var query = @"
                SELECT 
                    m.Name [ManufacturingArea], 
                    CASE WHEN i.RequireES11 = 1 THEN 'ES11' ELSE 'Incident' END [Type],
                    CASE WHEN DATEPART(HOUR, i.LocalActivityPerformedDateTime) < 7 THEN 3
                        WHEN DATEPART(HOUR, i.LocalActivityPerformedDateTime) < 15 THEN 1
                        WHEN DATEPART(HOUR, i.LocalActivityPerformedDateTime) < 23 THEN 2
                        ELSE 3 END [Shift],
                    i.EstimatedDownTimeHours
                FROM dbo.Incidents i
                INNER JOIN dbo.ManufacturingAreas m ON m.ManufacturingAreaId = i.ManufacturingAreaId
                WHERE i.LocalActivityPerformedDateTime >= DATEADD(DAY, -30, CAST(GETDATE() AS DATE))
                  AND i.ActivityTypeId <> 'M'";

            //How incidents (total) last 30 days?
            var incidentsLast30Days = await DatabaseContext.IncidentMetrics
                .FromSqlRaw(query)
                .ToListAsync();

            //How ES11s last 30 days?
            var es11sLast30Days = incidentsLast30Days
                .Where(i => i.Type == "ES11")
                .Count();
            Logger.LogTrace("es11sLast30Days = {es11sLast30Days}", es11sLast30Days);

            float downtimeLast30Days = 0f;

            if (incidentsLast30Days.Count > 0)
            {
                //What is average downtime last 30 days?
                downtimeLast30Days = incidentsLast30Days.Average(i => i.EstimatedDownTimeHours);
                Logger.LogTrace("downtimeLast30Days = {downtimeLast30Days}", downtimeLast30Days);
            
                //Which area has the most incidents last 30 days?
                var mostIncidents = (
                    from i in incidentsLast30Days
                    group i by i.ManufacturingArea into g
                    select new { ManufacturingArea = g.Key, Count = g.Count() }
                    ).OrderByDescending(i => i.Count)
                    .FirstOrDefault();

                string mostIncidentsLast30Days = $"{mostIncidents.ManufacturingArea} with {mostIncidents.Count}";
                Logger.LogTrace("mostIncidentsLast30Days = {mostIncidentsLast30Days}", mostIncidentsLast30Days);

                //get a count of incidents by type and shift
                var incidents =
                    from i in incidentsLast30Days
                    select new { i.Type, i.Shift };

                var incidentsByShift =
                    from i in incidents
                    group i by i.Type into g
                    select new HomeIncidentCountViewModel
                    {
                        Type = g.Key,
                        First = g.Where(i => i.Shift == 1).Count(),
                        Second = g.Where(i => i.Shift == 2).Count(),
                        Third = g.Where(i => i.Shift == 3).Count(),
                        Total = g.Count()
                    };

                //now calculate percentage of ES11s for each shift
                var percentES11ByShift =
                    from r in incidentsByShift
                    where r.Type == "ES11"
                    select new HomeES11PercentViewModel
                    {
                        Type = "Percentages",
                        First  = r.First > 0 ? Math.Round(r.First  * 100.0 / incidentsByShift.Sum(s => s.First), 0) : 0,
                        Second = r.Second > 0 ? Math.Round(r.Second * 100.0 / incidentsByShift.Sum(s => s.Second), 0) : 0,
                        Third  = r.Third > 0 ? Math.Round(r.Third  * 100.0 / incidentsByShift.Sum(s => s.Third), 0) : 0,
                        Total  = r.Total > 0 ? Math.Round(r.Total  * 100.0 / incidentsByShift.Sum(s => s.Total), 0) : 0
                    };

                //transfer the data
                ViewData["MostIncidentsLast30Days"] = mostIncidentsLast30Days;
                ViewData["IncidentsByShift"] = incidentsByShift.ToList();
                ViewData["PercentES11ByShift"] = percentES11ByShift.ToList();
            }
            else
            {
                ViewData["MostIncidentsLast30Days"] = "N/A";
                ViewData["IncidentsByShift"] = new List<HomeIncidentCountViewModel>
                {   new HomeIncidentCountViewModel
                    {
                        Type = "Total",
                        First = 0,
                        Second = 0,
                        Third = 0,
                        Total = 0
                    }
                };
                ViewData["PercentES11ByShift"] = new List<HomeES11PercentViewModel>
                {
                    new HomeES11PercentViewModel
                    {
                        Type = "Percentages",
                        First  = 0,
                        Second = 0,
                        Third  = 0,
                        Total  = 0
                    }
                };
            }

            ViewData["IncidentsLast30Days"] = incidentsLast30Days.Count;
            ViewData["ES11sLast30Days"] = es11sLast30Days;
            ViewData["DowntimeLast30Days"] = Convert.ToSingle(Math.Round(downtimeLast30Days, 1));
                        
            return View();
        }

        [Authorize(Roles = "cslg1.cslg.net\\KANBPL_APP_ENG_ES11_Admin")]
        public IActionResult Manage() => View();
        
        public IActionResult About() => View();

        public IActionResult Contact() => View();

        public IActionResult Privacy() => View();

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error() 
        {
            var exceptionHandlerPathFeature =
                HttpContext.Features.Get<IExceptionHandlerPathFeature>();

            var err = exceptionHandlerPathFeature?.Error;
            var vm = new ErrorViewModel
            {
                RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier,
                Message = err.Message
            };
            Logger.LogError("Error occured.  RequestId = {0}, Message = {1}", vm.RequestId, vm.Message);
            return View(vm);
        }
    }
}

iTracker Source Code 09212020/AutoIncidentTracking/Controllers/T3GroupsController.cs
using IncidentTracking.Data;
using IncidentTracking.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using System;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;

/// <remarks>
/// ================================================================================
/// MODULE:  T3GroupsController.cs
///         
/// PURPOSE:
/// This class represents the Tier3 groups controller which is responsible for 
/// handling all interactions between the groups model, related view 
/// models and associated views (user displays).
///         
/// Copyright:    ©2020 by E2i, Inc.
/// Created Date: 2020-04-29
/// Author:       Brad Robbins (brobbins@e2i.net)
///   
/// --------------------------------------------------------------------------------
/// Revision History:			
/// Author          Date        Description
/// Brad Robbins	2020-04-29  Initial version
/// Brad Robbins    2020-06-11  Added logging
/// ================================================================================
/// </remarks>

namespace IncidentTracking.Controllers
{
    [Authorize(Roles = "cslg1.cslg.net\\KANBPL_APP_ENG_ES11_Admin")]
    public class T3GroupsController : BaseController
    {
        public T3GroupsController(ApplicationDbContext context, IConfiguration config, ILogger<T3GroupsController> logger)
            : base(context, config, logger){}

        // GET: T3Groups
        public async Task<IActionResult> Index(string sortOrder, int? page)
        {
            Logger.LogTrace("T3Groups/Index called with [{sortOrder}] and page [{page}]", sortOrder, page);
            //setup sorting data
            ViewData["CurrentSort"] = sortOrder;
            ViewData["NameSortParam"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";

            var list = DatabaseContext.T3Groups.AsNoTracking();

            if (sortOrder == "name_desc")
                list = list.OrderByDescending(c => c.Name);
            else
                list = list.OrderBy(c => c.Name);

            var outList = await PaginatedList<T3Group>
                .CreateAsync(list, page ?? 1, PageSize);

            return View("Index", outList);
        }
        
        // GET: T3Groups/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            Logger.LogTrace("T3Groups/Details called with [{id}]", id);
            if (id == null)
                return NotFound();

            var group = await DatabaseContext.T3Groups
                .Include(g => g.ManufacturingAreas)
                .AsNoTracking()
                .FirstOrDefaultAsync(g => g.T3GroupId == id);
            if (group == null)
                return NotFound();

            return View(group);
        }

        // GET: T3Groups/Create
        public IActionResult Create() => View();

        // POST: T3Groups/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("T3GroupId,Name,SmeName,SmeEmailAddress,ReplyToEmailAddress")] T3Group group)
        {
            Logger.LogTrace("T3Groups/Create[Post] called");
            if (ModelState.IsValid)
            {
                try
                {
                    DatabaseContext.Add(group);
                    await DatabaseContext.SaveChangesAsync();
                    TempData["Message"] = "Group has been added.";
                    Logger.LogInformation("{user} added T3Group[{name}]", group.Name);
                    return RedirectToAction(nameof(Index));
                }
                catch (DbUpdateException)
                {
                    string message = "Cannot add group because ID is in use.";
                    TempData["Error"] = message;
                    Logger.LogDebug(message);
                }
                catch (SqlException ex)
                {
                    string message = $"Cannot add group because of a database error: {ex.Message}";
                    TempData["Error"] = message;
                    Logger.LogError(message);
                }
                catch (Exception ex)
                {
                    string message = $"Cannot add group because of a general error: {ex.Message}";
                    TempData["Error"] = message;
                    Logger.LogError(message);
                }
            }
            return View(group);
        }

        // GET: T3Groups/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            Logger.LogTrace("T3Groups/Edit[GET] called with [{id}]", id);
            if (id == null)
                return NotFound();

            var group = await DatabaseContext.T3Groups.FindAsync(id);
            if (group == null)
                return NotFound();
            return View(group);
        }

        // POST: T3Groups/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("T3GroupId,Name,SmeName,SmeEmailAddress,ReplyToEmailAddress")] T3Group group)
        {
            Logger.LogTrace("T3Groups/Edit[POST] called with [{id}]", id);
            if (id != group.T3GroupId)
                return NotFound();

            if (ModelState.IsValid)
            {
                try
                {
                    DatabaseContext.Update(group);
                    await DatabaseContext.SaveChangesAsync();
                    TempData["Message"] = "Group has been updated.";
                    Logger.LogInformation("{user} updated T3Group[{name}]", UserName, group.Name);
                }
                catch (DbUpdateConcurrencyException ex)
                {
                    string message;
                    if (!T3GroupExists(group.T3GroupId))
                        message = $"Cannot edit group because it no longer exists.";
                    else
                        message = $"Cannot edit group because of a concurrency error: {ex.Message}";
                    TempData["Error"] = message;
                    Logger.LogError("Error updating T3Group[{id}] because of {message}", id, message);
                }
                catch (Exception ex)
                {
                    string message = $"Cannot edit group because of a general error: {ex.Message}";
                    TempData["Error"] = message;
                     Logger.LogError("Error updating T3Group[{id}] because of {message}", id, message);
                }
                return RedirectToAction(nameof(Index));
            }
            return View(group);
        }

        // GET: T3Groups/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            Logger.LogTrace("T3Groups/Delete[GET] called with [{id}]", id);
            if (id == null)
                return NotFound();

            var group = await DatabaseContext.T3Groups
                .FirstOrDefaultAsync(g => g.T3GroupId == id);
            if (group == null)
                return NotFound();

            return View(group);
        }

        // POST: T3Groups/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            Logger.LogTrace("T3Groups/Delete[POST] called with [{id}]", id);
            try
            {
                var group = await DatabaseContext.T3Groups.FindAsync(id);
                DatabaseContext.T3Groups.Remove(group);
                await DatabaseContext.SaveChangesAsync();
                Logger.LogInformation("{user} deleted T3Group[{name}]", UserName, group.Name);
                TempData["Message"] = "Group has been deleted.";
            }
            catch (DbUpdateException)
            {
                TempData["Error"] = "Cannot delete an group that is in use.";
                Logger.LogDebug("Error deleting T3Group that is in user.");
            }
            catch (SqlException ex)
            {
                TempData["Error"] = $"Cannot delete group.  A database error occurred: {ex.Message}";
                Logger.LogError("Error deleting T3Group, SQL error: {message}", ex.Message);
            }
            catch (Exception ex)
            {
                TempData["Error"] = $"Cannot delete group.  A general error occurred: {ex.Message}";
                Logger.LogError("Error deleting T3Group, general error: {message}", ex.Message);
            }
            return RedirectToAction(nameof(Index));
        }

        private bool T3GroupExists(int id) => DatabaseContext.T3Groups.Any(g => g.T3GroupId == id);
    }
}

iTracker Source Code 09212020/AutoIncidentTracking/Views/Home/About.cshtml
@*
    * ================================================================================
    * MODULE:  Home\About.cshtml
    *
    * PURPOSE:
    * This view represents the about page.
    *
    * Copyright:    ©2018 by E2i, Inc.
    * Created Date: 2018-10-18
    * Author:       Brad Robbins (brobbins@e2i.net)
    *
    * --------------------------------------------------------------------------------
    * Revision History:
    * Author           Date        Description
    * Brad Robbins	   2018-10-30  Initial version
    * ================================================================================
*@
@{
    ViewData["Title"] = "About Incident Tracking Website";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<div class="row">
    <div class="col-md-4">
        <p>This application provides a means for engineers and support staff to log incidents
            and related ES11 data when interventions are made.  In addition, it provides basic
            reporting of incidents and serves as a searchable record of logged incidents.</p>
          
    </div>
</div>

<h2>Contact</h2>          
<address>
    E2i, Inc.<br />
    250 South Diversatech Drive<br />
    Manteno, IL  60950<br />
    <abbr title="Phone">P:</abbr>855-589-5571
</address>

<address>
    <strong>Support:</strong> <a href="mailto:brobbins@e2i.net">brobbins@e2i.net</a><br />
</address>

iTracker Source Code 09212020/AutoIncidentTracking/Views/Home/Contact.cshtml
@*
    * ================================================================================
    * MODULE:  Home\Contact.cshtml
    *
    * PURPOSE:
    * This view represents the contact page.
    *
    * Copyright:    ©2018 by E2i, Inc.
    * Created Date: 2018-10-18
    * Author:       Brad Robbins (brobbins@e2i.net)
    *
    * --------------------------------------------------------------------------------
    * Revision History:
    * Author           Date        Description
    * Brad Robbins	   2018-10-30  Initial version
    * ================================================================================
*@
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    E2i, Inc.<br />
    250 South Diversatech Drive<br />
    Manteno, IL  60950<br />
    <abbr title="Phone">P:</abbr>855-589-5571
</address>

<address>
    <strong>Support:</strong> <a href="mailto:brobbins@e2i.net">brobbins@e2i.net</a><br />
</address>

iTracker Source Code 09212020/AutoIncidentTracking/Views/Home/Index.cshtml
@*
    * ================================================================================
    * MODULE:  Home\Index.cshtml
    *
    * PURPOSE:
    * This view represents the front page of the wesite.
    *
    * Copyright:    ©2018 by E2i, Inc.
    * Created Date: 2018-10-18
    * Author:       Brad Robbins (brobbins@e2i.net)
    *
    * --------------------------------------------------------------------------------
    * Revision History:
    * Author           Date        Description
    * Brad Robbins	   2018-10-30  Initial version
    * Brad Robbins     2019-06-27  Removed report handling from config and replaced with direct links
    * Brad Robbins     2020-03-11  Re-enabled ES11 reporting
    * Brad Robbins     2020-03-16  Updated to Tier3 reports
    * Brad Robbins     2020-04-30  Added Tier 3 Group report button
    * ================================================================================
*@
@{
    ViewData["Title"] = "Home Page";
}
@{ var incidents = ViewData["IncidentsLast30Days"]; }
@{ var downtime = ViewData["DowntimeLast30Days"]; }
@{ var maxIncidents = ViewData["MostIncidentsLast30Days"]; }
@{ var incidentsByShift = ViewData["IncidentsByShift"] as List<HomeIncidentCountViewModel>; }
@{ var percentES11ByShift = ViewData["PercentES11ByShift"] as List<HomeES11PercentViewModel>; }

<style type="text/css">
    .carousel-caption { top: 0; bottom: auto; }
    .carousel-indicators { top: auto; bottom: 5%; }
    .white { color: white; }
    .black { color: black; }
</style>

<div id="myCarousel" class="carousel slide hidden-xs hidden-sm" data-ride="carousel" data-interval="8000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="Reported Incidents" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <a class="btn" href="#">
                    <h1 class="black">Incidents (30d): <strong>@incidents</strong></h1>
                </a>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Downtime" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <a class="btn" href="#">
                    <h1 class="white">Average Downtime (30d): <strong>@downtime <text>&nbsp;hrs</text></strong></h1>
                </a>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Most Incidents" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <a class="btn" href="#">
                    <h1 class="white">Most Incidents (30d): <strong>@maxIncidents</strong></h1>
                </a>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-1"></div>
    <div class="col-sm-4 col-md-3">
        <h2 class="text-center">Incidents</h2>
        <a class="btn btn-lg btn-primary btn-block" asp-controller="Incidents" asp-action="Create">Create an Incident</a>
        <a class="btn btn-lg btn-default btn-block" asp-controller="Incidents" asp-action="Index">View Incident Log</a>
        <a class="btn btn-lg btn-default btn-block" asp-controller="Incidents" asp-action="Search">Search Incident Log</a>
    </div>
    <div class="col-sm-4 col-md-3">
        <h2 class="text-center">Reports</h2>
        
        <a class="btn btn-lg btn-primary btn-block" href="http://pwkansql001/Reports/report/IncidentTrackingReports/Tier3?type=PCS">Tier 3 Report</a>
        <a class="btn btn-lg btn-default btn-block" href="http://pwkansql001/Reports/report/IncidentTrackingReports/Tier3H?type=PCS">Tier 3 Historical Report</a>
        <a class="btn btn-lg btn-default btn-block" href="http://pwkansql001/Reports/report/IncidentTrackingReports/Tier3Group">Tier 3 Group Report</a>
    </div>
    <div class="col-md-1"></div>
    <div class="col-sm-4 col-md-3">
        <br />
        <h4>Incidents By Shift (30d)</h4>
        <table class="table table-condensed">
            <thead>
                <tr>
                    <th>Type</th>
                    <th>1st</th>
                    <th>2nd</th>
                    <th>3rd</th>
                    <th>Total</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var i in incidentsByShift)
                {
                    <tr>
                        <td>@i.Type</td>
                        <td>@i.First</td>
                        <td>@i.Second</td>
                        <td>@i.Third</td>
                        <td>@i.Total</td>
                    </tr>
                }
            </tbody>
        </table>
        <br />
        <h4>ES11s By Shift (30d)</h4>
        <table class="table table-condensed">
            <thead>
                <tr>
                    <th>1st</th>
                    <th>2nd</th>
                    <th>3rd</th>
                    <th>Total</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var i in percentES11ByShift)
                {
                    <tr>
                        <td>@i.First%</td>
                        <td>@i.Second%</td>
                        <td>@i.Third%</td>
                        <td>@i.Total%</td>
                    </tr>
                }
            </tbody>
        </table>
        <br />
        <h4>Average Downtime (30d)</h4>
        <p>@downtime&nbsp;hrs</p>
    </div>
</div>

iTracker Source Code 09212020/AutoIncidentTracking/Views/Home/Manage.cshtml
@*
    * ================================================================================
    * MODULE:  Home\Manage.cshtml
    *
    * PURPOSE:
    * This view represents the manage page.
    *
    * Copyright:    ©2018 by E2i, Inc.
    * Created Date: 2018-10-18
    * Author:       Brad Robbins (brobbins@e2i.net)
    *
    * --------------------------------------------------------------------------------
    * Revision History:
    * Author           Date        Description
    * Brad Robbins	   2018-10-30  Initial version
    * Brad Robbins     2020-04-29  Added Manage Tier 3 Groups
    * ================================================================================
*@
@{
    ViewData["Title"] = "Site Management";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<div class="row">
    <div class="col-sm-4 col-md-3">
        <a class="btn btn-default btn-block" asp-controller="Classifications" asp-action="Index">Manage Classifications</a>
        <a class="btn btn-default btn-block" asp-controller="ManufacturingAreas" asp-action="Index">Manage Manufacturing Areas</a>
        <a class="btn btn-default btn-block" asp-controller="ControlSystems" asp-action="Index">Manage Control Systems</a>
        <a class="btn btn-default btn-block" asp-controller="T3Groups" asp-action="Index">Manage Tier 3 Groups</a>
    </div>
</div>