iTracker Source Code 09212020/MESIncidentTracking/Controllers/HomeController.cs
using ES13Web;
using ES13Web.Controllers;
using ES13Web.Data;
using ES13Web.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Diagnostics;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

/// <remarks>
/// ================================================================================
/// MODULE:  HomeController.cs
///         
/// PURPOSE:
/// This class is responsible for handling all static views (user displays).
///         
/// Copyright:    ©2018 by E2i, Inc.
/// Created Date: 2018-10-30
/// Author:       Brad Robbins (brobbins@e2i.net)
///   
/// --------------------------------------------------------------------------------
/// Revision History:			
/// Author          Date        Description
/// Brad Robbins	2018-10-30  Initial version
/// Brad Robbins    2019-06-03  Updated Index() to use LocalActivityPerformedDateTime
/// Brad Robbins    2020-06-10  Updated Index queries; removed unused report content
/// Brad Robbins    2020-06-15  Added logging
/// ================================================================================
/// </remarks>

namespace ES13Web.Controllers
{
    public class HomeController : BaseController
    {
        public HomeController(ApplicationDbContext context, IConfiguration config, ILogger<HomeController> logger)
            : base(context, config, logger){}

        public async Task<IActionResult> Index()
        {
            Logger.LogTrace("Home/Index called");
            var query = @"
                SELECT 
                    m.Name [ManufacturingArea], 
                    CASE WHEN i.RequireES13 = 1 THEN 'Intervention' ELSE 'Incident' END [Type],
                    CASE WHEN DATEPART(HOUR, i.LocalActivityPerformedDateTime) < 7 THEN 3
                        WHEN DATEPART(HOUR, i.LocalActivityPerformedDateTime) < 15 THEN 1
                        WHEN DATEPART(HOUR, i.LocalActivityPerformedDateTime) < 23 THEN 2
                        ELSE 3 END [Shift],
                    i.EstimatedDownTimeHours
                FROM dbo.Incidents i
                INNER JOIN dbo.ManufacturingAreas m ON m.ManufacturingAreaId = i.ManufacturingAreaId
                WHERE i.LocalActivityPerformedDateTime >= DATEADD(DAY, -30, CAST(GETDATE() AS DATE))";

            //How incidents (total) last 30 days?
            var incidentsLast30Days = await DatabaseContext.IncidentMetrics
                .FromSqlRaw(query)
                .ToListAsync();

            //How ES13s last 30 days?
            var interventionsLast30Days = incidentsLast30Days
                .Where(i => i.Type == "Intervention")
                .Count();
            Logger.LogTrace("interventionsLast30Days = {0}", interventionsLast30Days);

            float downtimeLast30Days = 0f;
            if (incidentsLast30Days.Count > 0)
            {
                //What is average downtime last 30 days?
                downtimeLast30Days =  incidentsLast30Days.Average(i => i.EstimatedDownTimeHours);
                Logger.LogTrace("downtimeLast30Days = {downtimeLast30Days}", downtimeLast30Days);

                //Which area has the most incidents last 30 days?
                var mostIncidents = (
                        from i in incidentsLast30Days
                        group i by i.ManufacturingArea into g
                        select new { ManufacturingArea = g.Key, Count = g.Count() }
                    ).OrderByDescending(i => i.Count)
                    .FirstOrDefault();

                string mostIncidentsLast30Days = $"{mostIncidents.ManufacturingArea} with {mostIncidents.Count}";
                Logger.LogTrace("mostIncidentsLast30Days = {mostIncidentsLast30Days}", mostIncidentsLast30Days);

                //get a count of incidents by type and shift
                var incidentsByShift =
                    from i in incidentsLast30Days
                    group i by i.Type into g
                    select new HomeIncidentCountViewModel
                    {
                        Type   = g.Key,
                        First  = g.Count(i => i.Shift == 1),
                        Second = g.Count(i => i.Shift == 2),
                        Third  = g.Count(i => i.Shift == 3),
                        Total  = g.Count()
                    };

                //now calculate percentage of ES13s for each shift
                var percentInterventionsByShift =
                    from r in incidentsByShift
                    where r.Type == "Intervention"
                    select new HomeES13PercentViewModel
                    {
                        Type = "Percentages",
                        First  = r.First == 0  ? 0 : Math.Round(r.First  * 100.0 / incidentsByShift.Sum(s => s.First), 0),
                        Second = r.Second == 0 ? 0 : Math.Round(r.Second * 100.0 / incidentsByShift.Sum(s => s.Second), 0),
                        Third  = r.Third == 0  ? 0 : Math.Round(r.Third  * 100.0 / incidentsByShift.Sum(s => s.Third), 0),
                        Total  = r.Total == 0  ? 0 : Math.Round(r.Total  * 100.0 / incidentsByShift.Sum(s => s.Total), 0)
                    };

                
                
                ViewData["MostIncidentsLast30Days"] = mostIncidentsLast30Days;
                ViewData["IncidentsByShift"] = incidentsByShift.ToList();
                ViewData["PercentInterventionsByShift"] = percentInterventionsByShift.ToList();
            }
            else
            {
                ViewData["MostIncidentsLast30Days"] = "N/A";
                ViewData["IncidentsByShift"] = new List<HomeIncidentCountViewModel>
                {   new HomeIncidentCountViewModel
                    {
                        Type = "Total",
                        First = 0,
                        Second = 0,
                        Third = 0,
                        Total = 0
                    }
                };
                ViewData["PercentInterventionsByShift"] = new List<HomeES13PercentViewModel>
                {
                    new HomeES13PercentViewModel
                    {
                        Type = "Percentages",
                        First  = 0,
                        Second = 0,
                        Third  = 0,
                        Total  = 0
                    }
                };
                
            }
            //transfer the data
            ViewData["IncidentsLast30Days"] = incidentsLast30Days.Count;
            ViewData["InterventionsLast30Days"] = interventionsLast30Days;
            ViewData["DowntimeLast30Days"] = Convert.ToSingle(Math.Round(downtimeLast30Days, 1));
            
            return View();
        }

        //[Authorize(Roles = "cslg1.cslg.net\\KANBPL_APP_ENG_ES11_Admin")]
        public IActionResult Manage() => View();
        
        public IActionResult About() => View();

        public IActionResult Contact() => View();

        public IActionResult Privacy() => View();

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error() 
        {
            var exceptionHandlerPathFeature =
                HttpContext.Features.Get<IExceptionHandlerPathFeature>();

            var err = exceptionHandlerPathFeature?.Error;
            var vm = new ErrorViewModel
            {
                RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier,
                Message = err.Message
            };
            Logger.LogError("Error occured.  RequestId = {0}, Message = {1}", vm.RequestId, vm.Message);
            return View(vm);
        }
    }
}

iTracker Source Code 09212020/MESIncidentTracking/Controllers/IncidentsController.cs
using ES13Web.Data;
using ES13Web.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Data;
using System.DirectoryServices.AccountManagement;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

/// <remarks>
/// ================================================================================
/// MODULE:  IncidentsController.cs
///         
/// PURPOSE:
/// This class represents the incident logs controller which is responsible for 
/// handling all interactions between the IncidentLog model, related view models 
/// and associated views (user displays).
///         
/// Copyright:    ©2019 by E2i, Inc.
/// Created Date: 2019-04-26
/// Author:       Brad Robbins (brobbins@e2i.net)
///   
/// --------------------------------------------------------------------------------
/// Revision History:			
/// Author          Date        Description
/// Brad Robbins	2019-04-26  Initial version
/// Brad Robbins    2019-08-18  Commented authorize lines to open access to domain users
/// Brad Robbins    2019-08-29  Added support for engineering time
/// Brad Robbins    2019-09-11  Changes for searching, adding/editing changes
/// Brad Robbins    2019-09-16  Revised GetFilteredSearchResults to add one day to end date
/// Brad Robbins    2019-10-04  Added support for batch number to index, details, export and search actions
/// Brad Robbins    2019-12-03  Added support for hidden UserId field
/// Brad Robbins    2019-12-06  Added UserId for Duplicate and Search actions
/// Brad Robbins    2020-03-18  Added escalation field
/// Brad Robbins    2020-06-15  Added logging; reworked Index/Search/Export filtering; relocated GetUserFullName to BaseController
/// ================================================================================
/// </remarks>

namespace ES13Web.Controllers
{
    public class IncidentsController : BaseController
    {
        public IncidentsController(ApplicationDbContext context, IConfiguration config, ILogger<IncidentsController> logger)
            : base(context, config, logger){}

        // GET: Incidents
        public async Task<IActionResult> Index(
            string sortOrder,
            string currentFilter,
            string searchString,
            int? page)
        {
            Logger.LogTrace("Incidents/Index called with [{sortOrder}], filter [{filter}], search [{search}] and page [{page}]", sortOrder, currentFilter, searchString, page);
            
            //setup sorting, paging, filtering data
            ViewData["CurrentSort"] = sortOrder;
            ViewData["DateSortParam"] = String.IsNullOrEmpty(sortOrder) ? "date_asc" : "";
            ViewData["MfgAreaSortParam"] = sortOrder == "mfg" ? "mfg_desc" : "mfg";
            ViewData["CauseSortParam"] = sortOrder == "cause" ? "cause_desc" : "cause";
            ViewData["EngineerSortParam"] = sortOrder == "engr" ? "engr_desc" : "engr";
            ViewData["ShortDescriptionSortParam"] = sortOrder == "dscrptn" ? "dscrptn_desc" : "dscrptn";
            ViewData["ResolvedSortParam"] = sortOrder == "resolved" ? "resolved_desc" : "resolved";
            ViewData["WerumSortParam"] = sortOrder == "werum" ? "werum_desc" : "werum";
            ViewData["BTSortParam"] = sortOrder == "bt" ? "bt_desc" : "bt";
            ViewData["Es13SortParam"] = sortOrder == "es13" ? "es13_desc" : "es13";
            ViewData["BatchSortParam"] = sortOrder == "batch" ? "batch_desc" : "batch";

            //apply current filter
            if (String.IsNullOrEmpty(searchString))
                searchString = currentFilter;
            else
                page = 1;

            ViewData["CurrentFilter"] = searchString;

            //Setup query because EF Core 3.1 doesn't like client-side LINQ.
            //It's okay because this is more efficient than LINQ anyway.
            var query = @"
                SELECT
                    IncidentId = i.IncidentId,
                    ActivityPerformedDateTime = i.ActivityPerformedDateTime,
                    FormattedLocalActivityPerformedDateTime = FORMAT(i.LocalActivityPerformedDateTime, @dateFormat),
                    ManufacturingAreaName = m.Name,
                    ClassificationName = c.Name,
                    EngineerName = i.EngineerName,
                    ShortDescription = i.ShortDescription,
                    RequireES13 = CAST(COALESCE(i.RequireES13, 0) AS BIT),
                    Resolved = CAST(COALESCE(i.Resolved, 0) AS BIT),
                    WerumTicket = i.WerumTicket,
                    BTServiceRequestNumber = i.BTServiceRequestNumber,
                    BatchNumber = i.BatchNumber,
                    UserId = i.UserId
                FROM dbo.Incidents i
                INNER JOIN dbo.ManufacturingAreas m ON m.ManufacturingAreaId = i.ManufacturingAreaId
                INNER JOIN dbo.Classifications c ON c.ClassificationId = i.ClassificationId";

            IQueryable<IncidentIndexViewModel> list;
            var dateFormat = new SqlParameter("dateFormat", SqlDbType.NVarChar, 40);
            dateFormat.Value = DateFormat;

            if (!String.IsNullOrEmpty(searchString))
            {
                query += @"
                WHERE @searchString IS NOT NULL AND (
                    i.WerumTicket LIKE '%' + @searchString + '%' OR
                    i.BTServiceRequestNumber LIKE '%' + @searchString + '%' OR
                    i.BatchNumber LIKE '%' + @searchString + '%' OR
                    m.Name LIKE '%' + @searchString + '%' OR
                    i.ShortDescription LIKE '%' + @searchString + '%' OR
                    c.Name LIKE '%' + @searchString + '%' OR
                    i.EngineerName LIKE '%' + @searchString + '%') OR @searchString IS NULL";
                var filter = new SqlParameter("searchString", SqlDbType.NVarChar, 50);
                filter.Value = searchString;
                list = DatabaseContext.IncidentLog
                    .FromSqlRaw(query, dateFormat, filter)
                    .AsNoTracking();
            }
            else
            {
                list = DatabaseContext.IncidentLog
                    .FromSqlRaw(query, dateFormat)
                    .AsNoTracking();
            }

            //determine proper sorting
            switch (sortOrder)
            {
                case "date_asc": list = list.OrderBy(i => i.ActivityPerformedDateTime); break;

                case "cause": list = list.OrderBy(i => i.ClassificationName).ThenByDescending(i => i.ActivityPerformedDateTime); break;
                case "cause_desc": list = list.OrderByDescending(i => i.ClassificationName).ThenByDescending(i => i.ActivityPerformedDateTime); break;

                case "mfg": list = list.OrderBy(i => i.ManufacturingAreaName).ThenByDescending(i => i.ActivityPerformedDateTime); break;
                case "mfg_desc": list = list.OrderByDescending(i => i.ManufacturingAreaName).ThenByDescending(i => i.ActivityPerformedDateTime); break;

                case "engr": list = list.OrderBy(i => i.EngineerName).ThenByDescending(i => i.ActivityPerformedDateTime); break;
                case "engr_desc": list = list.OrderByDescending(i => i.EngineerName).ThenByDescending(i => i.ActivityPerformedDateTime); break;

                case "dscrptn": list = list.OrderBy(i => i.ShortDescription).ThenByDescending(i => i.ActivityPerformedDateTime); break;
                case "dscrptn_desc": list = list.OrderByDescending(i => i.ShortDescription).ThenByDescending(i => i.ActivityPerformedDateTime); break;

                case "resolved": list = list.OrderBy(i => i.Resolved).ThenByDescending(i => i.ActivityPerformedDateTime); break;
                case "resolved_desc": list = list.OrderByDescending(i => i.Resolved).ThenByDescending(i => i.ActivityPerformedDateTime); break;

                case "werum": list = list.OrderBy(i => i.WerumTicket).ThenByDescending(i => i.ActivityPerformedDateTime); break;
                case "werum_desc": list = list.OrderByDescending(i => i.WerumTicket).ThenByDescending(i => i.ActivityPerformedDateTime); break;

                case "bt": list = list.OrderBy(i => i.BTServiceRequestNumber).ThenByDescending(i => i.ActivityPerformedDateTime); break;
                case "bt_desc": list = list.OrderByDescending(i => i.BTServiceRequestNumber).ThenByDescending(i => i.ActivityPerformedDateTime); break;
                
                case "es13": list = list.OrderBy(i => i.RequireES13).ThenByDescending(i => i.ActivityPerformedDateTime); break;
                case "es13_desc": list = list.OrderByDescending(i => i.RequireES13).ThenByDescending(i => i.ActivityPerformedDateTime); break;

                case "batch": list = list.OrderBy(i => i.BatchNumber).ThenByDescending(i => i.ActivityPerformedDateTime); break;
                case "batch_desc": list = list.OrderByDescending(i => i.BatchNumber).ThenByDescending(i => i.ActivityPerformedDateTime); break;
                
                default: list = list.OrderByDescending(i => i.ActivityPerformedDateTime); break;
            }

            var outList = await PaginatedList<IncidentIndexViewModel>
                .CreateAsync(list, page ?? 1, PageSize);
            ViewData["RowCount"] = list.Count();

            return View("Index", outList);
        }

        // GET: Incidents/Search
        public async Task<IActionResult> Search(
            DateTime? startDateTime = null,
            DateTime? endDateTime = null,
            int? manufacturingAreaId = null,
            int? classificationId = null,
            string engineerName = null,
            string shortDescription = null,
            string incidentDescription = null,
            string actionSummary = null,

iTracker Source Code 09212020/MESIncidentTracking/Views/Home/About.cshtml
@*
    * ================================================================================
    * MODULE:  Home\About.cshtml
    *
    * PURPOSE:
    * This view represents the about page.
    *
    * Copyright:    ©2019 by E2i, Inc.
    * Created Date: 2019-04-26
    * Author:       Brad Robbins (brobbins@e2i.net)
    *
    * --------------------------------------------------------------------------------
    * Revision History:
    * Author           Date        Description
    * Brad Robbins	   2019-04-26  Initial version
    * ================================================================================
*@
@{
    ViewData["Title"] = "About ES13 Web";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>
    This application provides a means for engineers and support staff to log incidents.
    In addition, it provides basic reporting of incidents and serves as a searchable 
    record of logged incidents.
</p>

<h2>Contact</h2>
<address>
    E2i, Inc.<br />
    250 South Diversatech Drive<br />
    Manteno, IL  60950<br />
    <abbr title="Phone">P:</abbr>855-589-5571
</address>

<address>
    <strong>Support:</strong> <a href="mailto:support@e2i.net">support@e2i.net</a><br />
</address>

iTracker Source Code 09212020/MESIncidentTracking/Views/Home/Contact.cshtml
@*
    * ================================================================================
    * MODULE:  Home\Contact.cshtml
    *
    * PURPOSE:
    * This view represents the contact page.
    *
    * Copyright:    ©2019 by E2i, Inc.
    * Created Date: 2019-04-26
    * Author:       Brad Robbins (brobbins@e2i.net)
    *
    * --------------------------------------------------------------------------------
    * Revision History:
    * Author           Date        Description
    * Brad Robbins	   2019-04-26  Initial version
    * ================================================================================
*@
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    E2i, Inc.<br />
    250 South Diversatech Drive<br />
    Manteno, IL  60950<br />
    <abbr title="Phone">P:</abbr>855-589-5571
</address>

<address>
    <strong>Support:</strong> <a href="mailto:support@e2i.net">support@e2i.net</a><br />
</address>

iTracker Source Code 09212020/MESIncidentTracking/Views/Home/Index.cshtml
@*
    * ================================================================================
    * MODULE:  Home\Index.cshtml
    *
    * PURPOSE:
    * This view represents the front page of the wesite.
    *
    * Copyright:    ©2019 by E2i, Inc.
    * Created Date: 2019-04-26
    * Author:       Brad Robbins (brobbins@e2i.net)
    *
    * --------------------------------------------------------------------------------
    * Revision History:
    * Author           Date        Description
    * Brad Robbins	   2019-04-26  Initial version
    * Brad Robbins     2019-06-27  Removed reports from config in favor of direct links
    * Brad Robbins     2019-09-30  Renamed "ES13%" to "Intervention %" in shift table
    * Brad Robbins     2020-03-16  Updated to Tier3 reports
    * ================================================================================
*@
@{
    ViewData["Title"] = "Home Page";
}
@{ var incidents = ViewData["IncidentsLast30Days"]; }
@{ var downtime = ViewData["DowntimeLast30Days"]; }
@{ var maxIncidents = ViewData["MostIncidentsLast30Days"]; }
@{ var incidentsByShift = ViewData["IncidentsByShift"] as List<HomeIncidentCountViewModel>; }
@{ var percentInterventionsByShift = ViewData["PercentInterventionsByShift"] as List<HomeES13PercentViewModel>; }
@{ var incidentsByDay = ViewData["IncidentsByDay"]; }

<style type="text/css">
    .carousel-caption { top: 0; bottom: auto; }
    .carousel-indicators { top: auto; bottom: 5%; }
    .white { color: white; }
    .black { color: black; }
</style>

<div id="myCarousel" class="carousel slide hidden-xs hidden-sm" data-ride="carousel" data-interval="8000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="Reported Incidents" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <a class="btn" href="#">
                    <h1 class="black">Incidents (30d): <strong>@incidents</strong></h1>
                </a>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Downtime" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <a class="btn" href="#">
                    <h1 class="white">Average Downtime (30d): <strong>@downtime <text>&nbsp;hrs</text></strong></h1>
                </a>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <a class="btn" href="#">
                    <h1 class="white">Most Incidents (30d): <strong>@maxIncidents</strong></h1>
                </a>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-sm-4 col-md-3">
        <h2 class="text-center">Incidents</h2>
        <a class="btn btn-lg btn-primary btn-block" asp-controller="Incidents" asp-action="Create">Create an Incident</a>
        <a class="btn btn-lg btn-default btn-block" asp-controller="Incidents" asp-action="Index">View Incident Log</a>
        <a class="btn btn-lg btn-default btn-block" asp-controller="Incidents" asp-action="Search">Search Incident Log</a>
    </div>
    <div class="col-sm-5 col-md-4">
        <h2 class="text-center">Reports</h2>
        
        <a class="btn btn-lg btn-primary btn-block" href="http://pwkansql001/Reports/report/IncidentTrackingReports/Tier3?type=MES">Tier 3 Report</a>
        <a class="btn btn-lg btn-default btn-block" href="http://pwkansql001/Reports/report/IncidentTrackingReports/Tier3H?type=MES">Tier 3 Historical Report</a>
        <a class="btn btn-lg btn-default btn-block" href="http://pwkansql001/Reports/report/IncidentTrackingReports/MES-UnresolvedIncidents">Unresolved Incidents Report</a>
        <a class="btn btn-lg btn-default btn-block" href="http://pwkansql001/Reports/report/IncidentTrackingReports/MES-UnresolvedWerumIncidents">Unresolved Werum Tickets Report</a>
    </div>
    <div class="col-md-1"></div>
    <div class="col-sm-4 col-md-3">
        <br />
        <h4>Incidents By Shift (30d)</h4>
        <table class="table table-condensed">
            <thead>
                <tr>
                    <th>Type</th>
                    <th class="text-right">1st</th>
                    <th class="text-right">2nd</th>
                    <th class="text-right">3rd</th>
                    <th class="text-right">Total</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var i in incidentsByShift)
                {
                    <tr>
                        <td>@i.Type</td>
                        <td class="text-right">@i.First</td>
                        <td class="text-right">@i.Second</td>
                        <td class="text-right">@i.Third</td>
                        <td class="text-right">@i.Total</td>
                    </tr>
                }
            
                @foreach (var i in percentInterventionsByShift)
                {
                    <tr>
                        <td>Intervention %</td>
                        <td class="text-right">@i.First%</td>
                        <td class="text-right">@i.Second%</td>
                        <td class="text-right">@i.Third%</td>
                        <td class="text-right">@i.Total%</td>
                    </tr>
                }
            </tbody>
        </table>
        <br />
        <h4>Average Downtime (30d)</h4>
        <p>@downtime&nbsp;hrs</p>
    </div>
</div>

iTracker Source Code 09212020/MESIncidentTracking/Views/Home/Manage.cshtml
@*
    * ================================================================================
    * MODULE:  Home\Manage.cshtml
    *
    * PURPOSE:
    * This view represents the manage page.
    *
    * Copyright:    ©2019 by E2i, Inc.
    * Created Date: 2019-04-26
    * Author:       Brad Robbins (brobbins@e2i.net)
    *
    * --------------------------------------------------------------------------------
    * Revision History:
    * Author           Date        Description
    * Brad Robbins	   2019-04-26  Initial version
    * ================================================================================
*@
@{
    ViewData["Title"] = "Site Management";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<div class="row">
    <div class="col-sm-4 col-md-3">
        <a class="btn btn-default btn-block" asp-controller="Classifications" asp-action="Index">Manage Classifications</a>
        <a class="btn btn-default btn-block" asp-controller="ManufacturingAreas" asp-action="Index">Manage Manufacturing Areas</a>
    </div>
</div>